services:
  web:
    build: ./app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: yobasystems/alpine-mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
