services:
  web:
    build: ./app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    platform: linux/amd64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
